name: "z Slack Notify"

on:
  workflow_dispatch:

jobs:
  notify:
    name: Slack notify
    runs-on: ubuntu-latest
    steps:
      - name: Slack notify
        uses: slackapi/slack-github-action@v2.0.0
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "C08D2JEK612"
            {
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "Hello World :ghost:"
                      }
                    },
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "Message Header",
                        "emoji": true
                      }
                    }
                  ]
                }
              ]
            }          
